---
title: "station-analysis"
author: "Julian DeGroot-Lutzner"
date: "12/14/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo= TRUE, message = FALSE, warning = FALSE,
                      fig.width = 7, fig.height = 4,
                      fig.align = "center")
options(digits=4)

require(dplyr)
require(ggplot2)
require(RMySQL)
require(lubridate)
require(ggmap)
require(readr)
require(chron)
require(caret)
```

```{r, cache=TRUE}
station_432 <- read.csv("station-432.csv")
station_521 <- read.csv("station-521.csv")
Weather_NYC <- read_csv("~/Documents/math154/ma154-project24-teambike/station-analysis/Weather_NYC.csv")
```

# HERE COULD BE MORE ANALYSIS ABOUT EACH STATION
How far does the average citibike move in a week?
Change avg. trip duration to median. 

```{r, cache= TRUE}
# Parsing all the start times into one format
mdy <- mdy_hms(station_432$starttime) 
ymd <- ymd_hms(station_432$starttime) 
f1 <- mdy_hm(station_432$starttime)
mdy[is.na(mdy)] <- ymd[is.na(mdy)] 
station_432$starttime <- mdy
station_432$starttime[is.na(station_432$starttime)] <- f1[is.na(station_432$starttime)]

# Parsing all the start times into one format
mdy <- mdy_hms(station_521$starttime) 
ymd <- ymd_hms(station_521$starttime) 
f1 <- mdy_hm(station_521$starttime)
mdy[is.na(mdy)] <- ymd[is.na(mdy)] 
station_521$starttime <- mdy
station_521$starttime[is.na(station_521$starttime)] <- f1[is.na(station_521$starttime)]
```

```
# took out rides that looped to the same station because these 
# rides don't impact our prediction model
median_ <- function(...) median(..., na.rm=T)

# weekly sums of station 521
weekly_sums_521 <- station_521 %>% 
  select(tripduration, starttime, start.station.id,
         end.station.id, usertype) %>%
  mutate(starttime = floor_date(starttime, "hour"),
         started.here = (start.station.id == 521),
         ended.here = (end.station.id == 521),
         subscriber = (usertype == "Subscriber"),
         customer = (usertype == "Customer")) %>%
  mutate(subscriber.started.here = 
           (started.here & !ended.here & subscriber),
         subscriber.ended.here = 
           (!started.here & ended.here & subscriber),
         customer.started.here = 
           (started.here & !ended.here & subscriber),
         customer.ended.here = 
           (!started.here & ended.here & subscriber)) %>%
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>%
  mutate(duration.from.start = 
          ifelse(started.here & !ended.here, tripduration, NA),
         duration.to.finish = 
          ifelse(!started.here & ended.here, tripduration, NA)) %>%
  group_by(starttime) %>%
  summarize(median.trip.from.521 = 
              median_(duration.from.start),
            median.trip.to.521 = 
              median_(duration.to.finish),
            num.subscribers.started.521 =
              sum(subscriber.started.here),
            num.subscribers.ended.521 =
              sum(subscriber.ended.here),
            num.customers.started.521 =
              sum(customer.started.here),
            num.customers.ended.521 =
              sum(customer.ended.here),
            total.trips.started.521 =
              sum(started.here & !ended.here),
            total.trips.ended.521 =
              sum(!started.here & ended.here))

# weekly sums for station 432
weekly_sums_432 <- station_432 %>% 
  select(tripduration, starttime, start.station.id,
         end.station.id, usertype) %>%
  mutate(starttime = floor_date(starttime, "week"),
         started.here = (start.station.id == 432),
         ended.here = (end.station.id == 432),
         subscriber = (usertype == "Subscriber"),
         customer = (usertype == "Customer")) %>%
  mutate(subscriber.started.here = 
           (started.here & !ended.here & subscriber),
         subscriber.ended.here = 
           (!started.here & ended.here & subscriber),
         customer.started.here = 
           (started.here & !ended.here & subscriber),
         customer.ended.here = 
           (!started.here & ended.here & subscriber)) %>%
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>%
  mutate(duration.from.start = 
          ifelse(started.here & !ended.here, tripduration, NA),
         duration.to.finish = 
          ifelse(!started.here & ended.here, tripduration, NA)) %>%
  group_by(starttime) %>%
  summarize(median.trip.from.432 = 
              median_(duration.from.start),
            median.trip.to.432 = 
              median_(duration.to.finish),
            num.subscribers.started.432 =
              sum(subscriber.started.here),
            num.subscribers.ended.432 =
              sum(subscriber.ended.here),
            num.customers.started.432 =
              sum(customer.started.here),
            num.customers.ended.432 =
              sum(customer.ended.here),
            total.trips.started.432 =
              sum(started.here & !ended.here),
            total.trips.ended.432 =
              sum(!started.here & ended.here))
hourly_station_data <- 
  left_join(hour_sums_432, hour_sums_521, by ="starttime")
```


#Hourly Sums
```{r, cache= TRUE}

# took out rides that looped to the same station because these 
# rides don't impact our prediction model
median_ <- function(...) median(..., na.rm=T)

# hourly sums of station 521
hourly_sums_521 <- station_521 %>% 
  select( starttime, start.station.id,
         end.station.id) %>%
  mutate(starttime = floor_date(starttime, "hour"),
         started.here = (start.station.id == 521),
         ended.here = (end.station.id == 521)) %>%
  group_by(starttime) %>%
  summarize(total.trips.started.521 =
              sum(started.here & !ended.here),
            total.trips.ended.521 =
              sum(!started.here & ended.here)) %>%
  mutate(net.change.521 = 
  total.trips.started.521 -total.trips.ended.521 )

# hourly sums for station 432
hourly_sums_432 <- station_432 %>% 
  select(starttime, start.station.id,
         end.station.id) %>%
  mutate(starttime = floor_date(starttime, "hour"),
         started.here = (start.station.id == 432),
         ended.here = (end.station.id == 432)) %>%
  group_by(starttime) %>%
  summarize(total.trips.started.432 =
              sum(started.here & !ended.here),
            total.trips.ended.432 =
              sum(!started.here & ended.here)) %>%
  mutate(net.change.432 = 
  total.trips.started.432 -total.trips.ended.432 )
```



Prepare the Weather Data
```{r,cache=TRUE}
# Choosing important variables
Weather_NYC <- Weather_NYC %>%
  select(valid, tmpf, dwpf, relh, vsby)
```

```{r, cache =TRUE}
Weather_NYC <- Weather_NYC %>% 
  mutate(valid = ymd_hms(valid)) %>%
  filter(minute(valid)=="51")  %>%
  mutate(valid = ceiling_date(valid, unit = "hour"),
         Month=month(valid)) %>%
  mutate( summer=ifelse(Month=="6"|Month=="7"|Month=="8",1,0),
          spring=ifelse((Month=="3"|Month=="4"|Month=="5"),1,0),
          winter=ifelse((Month=="1"|Month=="2"|Month=="12"),1,0),
          fall=ifelse((Month=="9"|Month=="10"|Month=="11"),1,0),
          day.of.week=wday(valid),
          hour = hour(valid)) %>%
  mutate(week.day=
           ifelse(day.of.week > 1 & day.of.week < 7,TRUE,FALSE),
         weekend.day=
           ifelse(day.of.week == 1 | day.of.week == 7,TRUE,FALSE),
         EarlyMorning=
           ifelse(hour=="0"|hour=="1"|hour=="2"|hour=="3"|hour=="4"|hour=="5"|hour=="6",1,0),
         Commuting=
           ifelse((hour=="7"|hour=="8"|hour=="9"),1,0),
         DayTime=
           ifelse((hour=="10"|hour=="11"|
              hour=="12"|hour=="13"|hour=="14"|hour=="15"),1,0),
         Evening=ifelse((hour=="16"|hour=="17"|
                           hour=="18"|hour=="19"),1,0),
         Night=ifelse((hour== "20"|
                         hour=="21"|hour=="22"|hour=="23"),1,0),
         starttime = valid) %>% 
  select(-valid, -hour, -Month, -day.of.week)

```

```{r,cache=TRUE}
station_432_combined <- hourly_sums_432 %>%
  select(starttime, net.change.432 ) %>%
  inner_join(Weather_NYC, by= "starttime" )
```

```{r,cache=TRUE}
station_521_combined <- hourly_sums_521 %>%
  select(starttime, net.change.521 ) %>%
  inner_join(Weather_NYC, by= "starttime" )
```

```{r,cache=TRUE}
print.data.frame(head(station_521_combined,1))
dim(station_521_combined)
print.data.frame(head(station_432_combined,1))
dim(station_432_combined)
```

```{r, cache=TRUE}
nrow(na.omit(station_521_combined))
```

```{r, cache=TRUE}
station_521_combined <- station_521_combined[complete.cases(station_521_combined),]
```

```{r,cache = TRUE}
station_521_combined <- station_521_combined %>%
  select(-starttime)
print.data.frame(head(station_521_combined,1))
dim(station_521_combined)
```

```{r, cache=TRUE}
set.seed(4747)
inTrain <- 
  createDataPartition(station_521_combined$net.change.521,
                      p = 0.7, list=FALSE)
training.521 <- station_521_combined[inTrain, ]
testing.521 <- station_521_combined[-inTrain,]
```


# Random Forest
Random Forest

How many trees is enough?
```{r,cache=TRUE}
#results <- data.frame()
#for(n in seq(from= 50, to = 750, by= 200)){
set.seed(47)
rf.model <- train(net.change.521~.,
                  data = training.521,
                  method = "rf",
                  trControl=trainControl(method="oob"),
                  ntree = 200,
                  tuneGrid=data.frame(mtry=6))
prediction <- predict(rf.model, testing.521)
#cm <- confusionMatrix(prediction, testing.521$)
#results <- rbind(results , cm$overall)
#}
#results

RMSE(prediction, testing.521$net.change.521)

```

```{r, cache = TRUE}
actual_positive_change <- (testing.521$net.change.521 > 0)
pred_positive_change <- (prediction > 0)
confusionMatrix(pred_positive_change, actual_positive_change)
all_true <- (prediction < -10000)
confusionMatrix(all_true, actual_positive_change)
```

```{r, cache =TRUE}
head(prediction)
head(testing.521$net.change.521)
mean(prediction)
```

#SVM
```{r, cache = TRUE
training.521 <- training.521 %>%
  mutate(net.change.521 = net.change.521 > 0) %>%
```