---
title: "sample-analysis"
author: "Julian DeGroot-Lutzner & Adi Salwan"
date: "12/13/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo= TRUE, message = FALSE, warning = FALSE,
                      fig.width = 7, fig.height = 4,
                      fig.align = "center")
options(digits=4)

require(dplyr)
require(ggplot2)
require(lubridate)
require(ggmap)

```
## f
```{r, cache=TRUE}
library(readr)
randomsample <- read_csv("~/Documents/math154/ma154-project24-teambike/final_project/randomsample.csv")
```



```{r,cache=TRUE}
start_sums <- randomsample %>%
  group_by(start.station.id) %>%
  summarize(start.station.longitude = mean(start.station.longitude),
            start.station.latitude = mean(start.station.latitude),
            total.time.out = sum(tripduration),
            start.count = n()) %>% 
  mutate(avg.time.out = total.time.out/start.count) %>%
  select(-total.time.out) %>% 
  ungroup()
```


The Map Used
```{r, cache = TRUE}
center.citibikes <- c(
  lon = mean(randomsample$start.station.longitude),
  lat = mean(randomsample$start.station.latitude))
mymap <- get_map(location = center.citibikes,
                 maptype = "roadmap",
                 zoom = 12)
```

Location of Stations Map
```{r, cache = TRUE}
 ggmap(mymap, extent = "panel", maprange=FALSE) +
  geom_density2d(data = start_sums, 
                           aes(x = start.station.longitude,
                               y = start.station.latitude)) +
  stat_density2d(data = start_sums, 
                           aes(x = start.station.longitude,
                               y = start.station.latitude, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 16, geom = 'polygon') +
  scale_fill_gradient(low = "green", high = "red") +
  scale_alpha(range = c(0.00, 0.25), guide = FALSE) +
  theme(legend.position = "none", axis.title = element_blank(), text = element_text(size = 12))
```

Count visualization Map
```{r, cache=TRUE}
ggmap(mymap) +  geom_point(data = start_sums, 
                           aes(x = start.station.longitude,
                               y = start.station.latitude,
                               fill = "red", alpha = start.count),
                           size = 1, shape = 21) +
  guides(fill=FALSE, alpha=FALSE, size=FALSE)
```

Avg. Trip Time Map
```{r, cache=TRUE}
ggmap(mymap) +  geom_point(data = start_sums, 
                           aes(x = start.station.longitude,
                               y = start.station.latitude,
                               fill = "red", alpha = avg.time.out),
                           size = 1, shape = 21) +
  guides(fill=FALSE, alpha=FALSE, size=FALSE)
```


```{r}
start_sums %>% 
  arrange(desc(start.count)) %>%
  select(-start.station.latitude, -start.station.longitude) %>%
  head()
start_sums %>% 
  arrange(desc(avg.time.out)) %>%
  select(-start.station.latitude, -start.station.longitude) %>%
  head()
```

```{r,cache= TRUE }
end_sums <- randomsample %>%
  group_by(end.station.id) %>%
  summarize(end.station.longitude = mean(end.station.longitude),
            end.station.latitude = mean(end.station.latitude),
            total.time.in = sum(tripduration),
            end.count = n()) %>% 
  mutate(avg.time.in = total.time.in/end.count) %>%
  select(-total.time.in) %>% 
  ungroup()
```

```{r}
colnames(start_sums)[1]<- c("id")
colnames(end_sums)[1] <- c("id")
joined_data<-inner_join(start_sums,end_sums,by="id")
joined_data <- joined_data %>%
mutate(difference = start.count - end.count,
       station.latitude = 
         (start.station.latitude+ end.station.latitude)/2,
       station.longitude = 
         (start.station.longitude + end.station.longitude)/2,
       total.ride.count = start.count + end.count) %>%
  mutate(normalized.difference =
           difference/(start.count+end.count),
         positive.difference = difference>0) %>%
  select(-start.station.latitude,
         -start.station.longitude,
         -end.station.longitude,
         -end.station.latitude) 
```


```{r}

```

```{r
ggplot(data = start_sums, aes(x=total.ride.count)) +
  geom_histogram()

```


```{r}
top_ten_perc <- joined_data$total.ride.count %>% 
  quantile(0.90)
```


```{r}
biggest_differences <- joined_data %>% 
  filter(total.ride.count >= top_ten_perc) %>%
  arrange(desc(normalized.difference)) %>%
head(10)
biggest_differences %>% 
    select(id, start.count, end.count, 
           difference, normalized.difference)

smallest_differences <- joined_data %>% 
  filter(total.ride.count >= top_ten_perc) %>%
  arrange(normalized.difference) %>%
head(10)
smallest_differences %>%
  select(id, start.count, end.count, 
         difference, normalized.difference)
```

Difference visualization Map
```{r, cache=TRUE}
ggmap(mymap) +  geom_point(data = joined_data, 
                           aes(x = station.longitude,
                               y = station.latitude,
                               fill = positive.difference, 
                               alpha = 0.7),
                           size = 1, shape = 21) +
  guides(fill=FALSE, alpha=FALSE, size=FALSE) +
  geom_point(data=biggest_differences,
             aes(x = station.longitude,
                 y = station.latitude,
                 fill = "blue",
                 alpha = 1.0),
             size = 1, shape = 21) +
    geom_point(data=smallest_differences,
             aes(x = station.longitude,
                 y = station.latitude,
                 fill = "red",
                 alpha = 1.0),
             size = 1, shape = 21)
```

```{r}
ggmap(mymap) +  
    geom_point(data=smallest_differences,
             aes(x = station.longitude,
                 y = station.latitude,
                 fill = "blue",
                 alpha = 1.0),
             size = 1, shape = 21) + 
  guides(fill=FALSE, alpha=FALSE, size=FALSE)
```

```{r}
ggmap(mymap) +  
  geom_point(data=biggest_differences,
             aes(x = station.longitude,
                 y = station.latitude,
                 fill = "red",
                 alpha = 1.0),
             size = 1, shape = 21) +
  guides(fill=FALSE, alpha=FALSE, size=FALSE) 
```

```{r}
head(joined_data)
stations_of_interest <- joined_data %>% 
  filter(id == 521 | id == 432)
stations_of_interest
```

```{r}
ggmap(mymap) +  
  geom_point(data=stations_of_interest,
             aes(x = station.longitude,
                 y = station.latitude,
                 fill = positive.difference,
                 alpha = 1.0),
             size = 4, shape = 21) +
  guides(fill=FALSE, alpha=FALSE, size=FALSE) 
```

